/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const PortfolioEntry = IDL.Record({
  'id' : IDL.Nat,
  'stockName' : IDL.Text,
  'sector' : IDL.Text,
  'addedAt' : Time,
  'buyPrice' : IDL.Float64,
  'quantity' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DailyInsight = IDL.Record({
  'ticker' : IDL.Text,
  'fetchedAt' : IDL.Int,
  'name' : IDL.Text,
  'cachedDate' : IDL.Text,
  'riskLevel' : IDL.Text,
  'reason' : IDL.Text,
});
export const Asset = IDL.Record({
  'ticker' : IDL.Text,
  'name' : IDL.Text,
  'rupeeAmount' : IDL.Float64,
  'allocation' : IDL.Float64,
  'riskScore' : IDL.Nat,
  'reason' : IDL.Text,
});
export const Query = IDL.Record({
  'suggestions' : IDL.Vec(Asset),
  'timestamp' : Time,
  'budget' : IDL.Float64,
  'riskLevel' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addInvestment' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [PortfolioEntry],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearManualPrice' : IDL.Func([IDL.Text], [], []),
  'clearQueryHistory' : IDL.Func([], [IDL.Bool], []),
  'deleteInvestment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteQuery' : IDL.Func([Time], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyInsight' : IDL.Func([], [DailyInsight], []),
  'getInvestmentSuggestions' : IDL.Func(
      [IDL.Float64, IDL.Text],
      [IDL.Vec(Asset)],
      [],
    ),
  'getInvestments' : IDL.Func([], [IDL.Vec(PortfolioEntry)], ['query']),
  'getManualPrice' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Float64)], ['query']),
  'getQueries' : IDL.Func([IDL.Nat], [IDL.Vec(Query)], ['query']),
  'getQueryHistory' : IDL.Func([], [IDL.Vec(Query)], ['query']),
  'getStockPrice' : IDL.Func([IDL.Text], [IDL.Float64], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'refreshDailyInsight' : IDL.Func([], [DailyInsight], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveManualPrice' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'suggestSector' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformDailyInsight' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const PortfolioEntry = IDL.Record({
    'id' : IDL.Nat,
    'stockName' : IDL.Text,
    'sector' : IDL.Text,
    'addedAt' : Time,
    'buyPrice' : IDL.Float64,
    'quantity' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DailyInsight = IDL.Record({
    'ticker' : IDL.Text,
    'fetchedAt' : IDL.Int,
    'name' : IDL.Text,
    'cachedDate' : IDL.Text,
    'riskLevel' : IDL.Text,
    'reason' : IDL.Text,
  });
  const Asset = IDL.Record({
    'ticker' : IDL.Text,
    'name' : IDL.Text,
    'rupeeAmount' : IDL.Float64,
    'allocation' : IDL.Float64,
    'riskScore' : IDL.Nat,
    'reason' : IDL.Text,
  });
  const Query = IDL.Record({
    'suggestions' : IDL.Vec(Asset),
    'timestamp' : Time,
    'budget' : IDL.Float64,
    'riskLevel' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addInvestment' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [PortfolioEntry],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearManualPrice' : IDL.Func([IDL.Text], [], []),
    'clearQueryHistory' : IDL.Func([], [IDL.Bool], []),
    'deleteInvestment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteQuery' : IDL.Func([Time], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyInsight' : IDL.Func([], [DailyInsight], []),
    'getInvestmentSuggestions' : IDL.Func(
        [IDL.Float64, IDL.Text],
        [IDL.Vec(Asset)],
        [],
      ),
    'getInvestments' : IDL.Func([], [IDL.Vec(PortfolioEntry)], ['query']),
    'getManualPrice' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Float64)], ['query']),
    'getQueries' : IDL.Func([IDL.Nat], [IDL.Vec(Query)], ['query']),
    'getQueryHistory' : IDL.Func([], [IDL.Vec(Query)], ['query']),
    'getStockPrice' : IDL.Func([IDL.Text], [IDL.Float64], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'refreshDailyInsight' : IDL.Func([], [DailyInsight], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveManualPrice' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'suggestSector' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformDailyInsight' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };