/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Asset {
  'ticker' : string,
  'name' : string,
  'rupeeAmount' : number,
  'allocation' : number,
  'riskScore' : bigint,
  'reason' : string,
}
export interface PortfolioEntry {
  'id' : bigint,
  'stockName' : string,
  'addedAt' : Time,
  'buyPrice' : number,
  'quantity' : number,
}
export interface Query {
  'suggestions' : Array<Asset>,
  'timestamp' : Time,
  'budget' : number,
  'riskLevel' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInvestment' : ActorMethod<[string, number, number], PortfolioEntry>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearQueryHistory' : ActorMethod<[], boolean>,
  'deleteInvestment' : ActorMethod<[bigint], boolean>,
  'deleteQuery' : ActorMethod<[Time], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInvestmentSuggestions' : ActorMethod<[number, string], Array<Asset>>,
  'getInvestments' : ActorMethod<[], Array<PortfolioEntry>>,
  'getQueries' : ActorMethod<[bigint], Array<Query>>,
  'getQueryHistory' : ActorMethod<[], Array<Query>>,
  'getStockPrice' : ActorMethod<[string], number>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
